version: "3.8"
services:
  # nginx:
  #   image: booking_nginx_i
  #   build:
  #     context: .
  #     dockerfile: "Dockerfile.nginx"
  #   container_name: booking_nginx
  #   ports:
  #      - 80:80
  #      - 443:443
  #   links:
  #      - booking
  #      # - flower
  #   volumes:
  #     - booking_static:/static
  
  postgres-db:
    image: postgres:16
    container_name: booking_db
    env_file:
      - .prod.env
    # network_mode: host
    ports:
      - 5433:5432
    volumes:
      - booking_pg_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:7
  #   container_name: booking_redis
  #   # ports:
  #   #   - 6379:6379

  booking:
    image: booking_app_i
    build:
      context: .
    container_name: booking_app
    env_file:
      - .prod.env
    depends_on:
      - postgres-db
      # - redis
    # command: ["/booking/docker/app.sh"]
    command: bash -c "sleep 5 && alembic upgrade head && uvicorn app:create_app --factory --host 0.0.0.0"
    # restart: always
    # volumes:
    #   - booking_static:/booking/static
    ports:
      - 7777:8000

  #celery:
  #  image: booking_celery_i
  #  build:
  #    context: .
  #  container_name: booking_celery
  #  env_file:
  #    - .prod.env
  #  depends_on:
  #    - redis
  #  command: ["/booking/docker/celery.sh", "celery"]
#
  #flower:
  #  image: booking_flower_i
  #  build:
  #    context: .
  #  container_name: booking_flower
  #  env_file:
  #    - .prod.env
  #  depends_on:
  #    - redis
  #  command: ["/booking/docker/celery.sh", "flower"]
  #  # ports:
  #  #   - 5555:5555

volumes:
  booking_pg_data:
  # booking_static: