version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: "Dockerfile.nginx"
    container_name: booking_nginx
    ports:
       - 80:80
       - 443:443
    links:
       - booking
       - flower
  
  db:
    image: postgres:16
    container_name: booking_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .prod.env
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    image: booking_image
    build:
      context: .
    container_name: booking_app
    env_file:
      - .prod.env
    depends_on:
      - db
      - redis
    command: ["/booking/docker/app.sh"]
    # ports:
    #   - 7777:8000

  celery:
    image: booking_celery
    build:
      context: .
    container_name: booking_celery
    command: ["/booking/docker/celery.sh", "celery"]
    env_file:
      - .prod.env
    depends_on:
      - redis

  flower:
    image: booking_flower
    build:
      context: .
    container_name: booking_flower
    command: ["/booking/docker/celery.sh", "flower"]
    env_file:
      - .prod.env
    depends_on:
      - redis
    # ports:
    #   - 5555:5555

volumes:
  postgresdata: