version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: "Dockerfile.nginx"
    container_name: booking_nginx
    ports:
       - 80:80
       - 443:443
    links:
       - booking
  
  db:
    image: postgres:16
    container_name: booking_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .prod.env
    ports:
      - 5432:5432

  booking:
    image: booking_image
    build:
      context: .
    container_name: booking_app
    env_file:
      - .prod.env
    depends_on:
      - db
    command: ["/booking/docker/app.sh"]
    # ports:
    #   - 7777:8000
  
volumes:
  postgresdata: